source 'https://rubygems.org'
gem "fusuma"
gem "fusuma-plugin-appmatcher"
gem "fusuma-plugin-keypress"
gem "fusuma-plugin-sendkey"
gem "fusuma-plugin-wmctrl"
gem "fusuma-plugin-touchscreen"

# I've not activated the following plugins for the reasons given below.

# tap has been archived by upstream
# gem "fusuma-plugin-tap"

# thumbsense pulls in remap, and at best remap requires further configuration to allow the use access to event devices.
#gem "fusuma-plugin-thumbsense"
#gem "fusuma-plugin-remap"
